### ISSUE TITLE
Missing config.js

### ISSUE THREAD

**Issue by peterj** [joshghent/PeepShowBot#9]
Project is missing the config.js file that's being referenced in `bot.js`
```
const config = require('./config.js');
```

**Comment by joshghent** [comment]
@peterj Yes very good point, this should be an object exporting the discord bot token.
Let's change it over to use [dotenv](https://www.npmjs.com/package/dotenv). It will allow us to edit the config variables with greater ease in the docker file.

Let me know if you want to handle this 👍 And good spot!
